name = "glambda"
version = "0.1.0"

description = "Write AWS Lambda functions in Gleam!"
licences = ["Apache-2.0"]
repository = { type = "github", user = "ryanmiville", repo = "glambda" }

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 0.13.0 and < 1.0.0"
gleam_http = ">= 3.7.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
birdie = ">= 1.2.3 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
